# Generated by Django 3.0.5 on 2020-06-08 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandType', models.TextField()),
                ('city', models.TextField()),
                ('assemblyType', models.TextField(default='local')),
                ('price', models.IntegerField(default=0)),
                ('engineCapacity', models.IntegerField()),
                ('registrationCity', models.IntegerField()),
                ('yearlyModel', models.TextField()),
                ('brandModel', models.TextField()),
                ('engineType', models.TextField()),
                ('color', models.TextField()),
                ('engineDetail', models.TextField(default='Petrol')),
                ('Mileage', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='houseParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseSize', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)])),
                ('price', models.BigIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5000000000000), django.core.validators.MinValueValidator(0)])),
                ('town', models.TextField()),
                ('age', models.IntegerField()),
                ('floor', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('isBasement', models.BooleanField()),
                ('isGarden', models.BooleanField()),
                ('servantRooms', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)])),
                ('numberOfBeds', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)])),
                ('distanceFromPark', models.IntegerField(default=0)),
                ('distanceFromMosque', models.IntegerField(default=0)),
                ('distanceFromSchool', models.IntegerField(default=0)),
                ('distanceFromMarket', models.IntegerField(default=0)),
                ('distanceFromHospital', models.IntegerField(default=0)),
            ],
        ),
    ]
