# Generated by Django 3.0.2 on 2020-07-23 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200723_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseparameters',
            name='bathroom',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)]),
        ),
    ]
