# Generated by Django 3.0.2 on 2020-07-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_houseparameters_bathroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carparameters',
            name='assemblyType',
            field=models.TextField(choices=[('Local', 'Local'), ('Imported', 'Imported')], default='local'),
        ),
        migrations.AlterField(
            model_name='carparameters',
            name='brandModel',
            field=models.TextField(choices=[('GLI', 'GLI'), ('XLI', 'XLI'), ('Mehran', 'Mehran'), ('Alto', 'Alto')]),
        ),
        migrations.AlterField(
            model_name='carparameters',
            name='engineType',
            field=models.TextField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')]),
        ),
    ]
